name: Build iOS App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.0.app
      - name: Build .ipa
        run: |
          xcodebuild -scheme YourScheme -sdk iphoneos -configuration Release archive -archivePath $PWD/build/App.xcarchive
          xcodebuild -exportArchive -archivePath $PWD/build/App.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath $PWD/build
      - name: Upload .ipa
        uses: actions/upload-artifact@v4
        with:
          name: ipa
          path: build/*.ipa
